### PR TITLE
update mtbench-evaluator

### PR DESCRIPTION
**Pull request by sallyom**
This PR updates MT_Bench to use `MTBenchEvaluator`. 

Note: Testing this, please don't merge.

### CODE REVIEW

**Comment by sallyom** [comment]
[test-run](https://rhods-dashboard-redhat-ods-applications.apps.ocp-beta-test.nerc.mghpcc.org/pipelines/ilab/a29a8d2b-7b8b-4b6a-934e-78bdf034af1d/a24d05eb-b253-410d-b342-90f08b7d97b7/runs/01b54d7c-ccb5-4d56-a7ed-ce6681c248b1)

**Comment by cooktheryan** [comment]
relaunching here https://rhods-dashboard-redhat-ods-applications.apps.ocp-beta-test.nerc.mghpcc.org/pipelines/ilab/a29a8d2b-7b8b-4b6a-934e-78bdf034af1d/1b2fbc2a-1128-4260-890c-8a89bf352a25/runs/2e298542-b91c-4774-a2c8-8d3a2641e137

**Comment by sallyom** [comment]
this should be all set - if [this run ](https://rhods-dashboard-redhat-ods-applications.apps.ocp-beta-test.nerc.mghpcc.org/pipelines/ilab/a29a8d2b-7b8b-4b6a-934e-78bdf034af1d/4acaaee4-9ab0-47f5-840d-87c03ec620f4/runs/ffb9e927-6cb8-48ad-8eab-d7f6d0362cd1)goes green

**Comment by sallyom** [comment]
@MichaelClifford @cooktheryan ptal

**Comment by leseb** [comment]
Please install https://docs.astral.sh/ruff/installation/ on your system and run `ruff format .` once https://github.com/redhat-et/ilab-on-ocp/pull/57 is merged. THEN rebase your PR, everything should go fine :).

**Comment by MichaelClifford** [comment]
@sallyom can you rebase this to pull in the linting changes?

**Comment by sallyom** [comment]
green run: https://rhods-dashboard-redhat-ods-applications.apps.ocp-beta-test.nerc.mghpcc.org/pipelines/ilab/c47684e9-299b-4817-95be-b310d6f120e4/19b2b401-cf8d-46bc-988f-5341530feb88/runs/9459933c-5bdd-419d-82de-bf3bd293e7a3

**Review by MichaelClifford — APPROVED** [review]
LGTM!

**Pull request merged**
