### PR TITLE
fix: use separate model checkpoint directories for each training phase

### LINKED ISSUE #131: Make sure each phase of training stores checkpoints in appropriate directories in KFP

### PR DESCRIPTION
**Pull request by MichaelClifford**
closes #131 

This PR adds a `phase_1` and `phase_2` directories for storing model checkpoints for each training phase.

### CODE REVIEW

**Review by tumido — APPROVED** [review]
/lgtm
/approve

**Review by sallyom — APPROVED** [review]
lgtm!

**Comment by sallyom** [comment]
[test-run](https://rhods-dashboard-redhat-ods-applications.apps.ocp-beta-test.nerc.mghpcc.org/pipelines/ilab/f3215dac-35a4-477f-85bb-c30df0048a87/239a1e43-00ff-47ed-a5e2-6f213746b33c/runs/56df35fe-3f73-472e-90fc-662e48dba4a0) (with #126 also)

**Comment by sallyom** [comment]
looks good! 2 models for 2 epochs phase 2

Screenshot 2024-10-30 at 10 54 14 AM

**Pull request merged**
